# Generated by Django 5.2.5 on 2026-02-27 22:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0003_reconocimientofacial_intentoreconocimientofacial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PiezaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_inventario', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('numero_serie', models.CharField(blank=True, max_length=100, unique=True)),
                ('numero_factura', models.CharField(blank=True, max_length=100)),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('peso', models.CharField(blank=True, help_text='Ej: 12.5 kg', max_length=50)),
                ('dimensiones', models.CharField(blank=True, help_text='Ej: 30x20x15 cm', max_length=150)),
                ('centro_formacion', models.CharField(blank=True, max_length=200)),
                ('ambiente_formacion', models.CharField(blank=True, max_length=200)),
                ('ubicacion', models.CharField(blank=True, max_length=200)),
                ('proveedor', models.CharField(blank=True, max_length=200)),
                ('valor_adquisicion', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('garantia_meses', models.PositiveIntegerField(default=0)),
                ('horas_uso', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('horas_uso_maximas', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('condicion', models.CharField(choices=[('nueva', 'Nueva'), ('usada', 'Usada'), ('cambiada', 'Cambiada'), ('dañada', 'Dañada')], default='nueva', max_length=20)),
                ('especificaciones_tecnicas', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piezas_registradas', to='usuarios.usuario')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piezas_responsable', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Pieza de Inventario',
                'verbose_name_plural': 'Piezas de Inventario',
                'ordering': ['-fecha_registro'],
                'indexes': [models.Index(fields=['codigo_inventario'], name='inventario__codigo__26df8f_idx'), models.Index(fields=['condicion'], name='inventario__condici_8571b3_idx')],
            },
        ),
    ]
