# Generated by Django 5.2.5 on 2026-02-27 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='piezainventario',
            name='foto_empaque',
            field=models.ImageField(blank=True, help_text='Fotografía del empaque', null=True, upload_to='inventario/empaques/'),
        ),
        migrations.AddField(
            model_name='piezainventario',
            name='foto_pieza',
            field=models.ImageField(blank=True, help_text='Fotografía de la pieza', null=True, upload_to='inventario/piezas/'),
        ),
    ]
