# Generated by Django 5.2.5 on 2026-02-10 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_tokenrecuperacionpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconocimientoFacial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', models.JSONField(help_text='Vector de características faciales (128 dimensiones)')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True, help_text='Indica si el reconocimiento facial está activo para este usuario')),
                ('confianza_registro', models.FloatField(help_text='Nivel de confianza de la detección facial durante el registro (0-1)')),
                ('ip_registro', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent_registro', models.TextField(blank=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reconocimiento_facial', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Reconocimiento Facial',
                'verbose_name_plural': 'Reconocimientos Faciales',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='IntentoReconocimientoFacial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_intento', models.CharField(choices=[('registro', 'Registro de rostro'), ('login', 'Inicio de sesión'), ('actualizacion', 'Actualización de rostro')], max_length=20)),
                ('resultado', models.CharField(choices=[('exitoso', 'Exitoso'), ('fallido', 'Fallido'), ('error', 'Error técnico')], max_length=20)),
                ('similitud', models.FloatField(blank=True, help_text='Nivel de similitud calculado (0-1)', null=True)),
                ('mensaje_error', models.TextField(blank=True)),
                ('fecha_intento', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intentos_reconocimiento', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Intento de Reconocimiento Facial',
                'verbose_name_plural': 'Intentos de Reconocimiento Facial',
                'ordering': ['-fecha_intento'],
                'indexes': [models.Index(fields=['usuario', '-fecha_intento'], name='usuarios_in_usuario_75610c_idx'), models.Index(fields=['resultado', '-fecha_intento'], name='usuarios_in_resulta_7c60b9_idx')],
            },
        ),
    ]
