# Generated by Django 5.2.5 on 2026-04-09 01:10
# Migración adaptada al estado real de la BD (columna ya renombrada parcialmente)

import django.db.models.deletion
from django.db import migrations, models


def arreglar_centro_formacion_en_bd(apps, schema_editor):
    """
    Estado real de la BD:
    - centro_formacion_id: VARCHAR(200) NULL  → hay que convertir a BIGINT INT FK
    - ficha_id: BIGINT NULL FK                → ya está correcto, nada que hacer
    """
    conn = schema_editor.connection
    with conn.cursor() as cursor:
        # 1. Limpiar todos los valores de texto (ninguno es un ID numérico)
        cursor.execute("UPDATE usuarios_usuario SET centro_formacion_id = NULL")

        # 2. Verificar si ya existe la FK constraint para no duplicarla
        cursor.execute(
            "SELECT CONSTRAINT_NAME FROM information_schema.KEY_COLUMN_USAGE "
            "WHERE TABLE_SCHEMA = DATABASE() "
            "AND TABLE_NAME = 'usuarios_usuario' "
            "AND COLUMN_NAME = 'centro_formacion_id' "
            "AND REFERENCED_TABLE_NAME IS NOT NULL"
        )
        existing_fk = cursor.fetchone()

    if existing_fk:
        # Ya tiene FK constraint, solo verificamos que el tipo sea correcto
        schema_editor.execute(
            "ALTER TABLE usuarios_usuario "
            "MODIFY COLUMN centro_formacion_id BIGINT NULL"
        )
    else:
        # Cambiar tipo y agregar FK
        schema_editor.execute(
            "ALTER TABLE usuarios_usuario "
            "MODIFY COLUMN centro_formacion_id BIGINT NULL, "
            "ADD CONSTRAINT fk_usuario_centro "
            "FOREIGN KEY (centro_formacion_id) "
            "REFERENCES sistema_centroformacion(id) ON DELETE SET NULL"
        )


class Migration(migrations.Migration):

    # MySQL no soporta DDL transaccional
    atomic = False

    dependencies = [
        ('sistema', '0004_ficha'),
        ('usuarios', '0003_reconocimientofacial_intentoreconocimientofacial'),
    ]

    operations = [
        # Toda la lógica de BD se hace en RunPython
        # Estado de Django se actualiza vía SeparateDatabaseAndState
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    arreglar_centro_formacion_en_bd,
                    migrations.RunPython.noop
                ),
            ],
            state_operations=[
                # ficha_id ya existe en BD, solo actualizamos el estado
                migrations.AddField(
                    model_name='usuario',
                    name='ficha',
                    field=models.ForeignKey(
                        blank=True, null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='sistema.ficha',
                        verbose_name='Ficha'
                    ),
                ),
                # centro_formacion ya está arreglado en BD, solo actualizamos el estado
                migrations.AlterField(
                    model_name='usuario',
                    name='centro_formacion',
                    field=models.ForeignKey(
                        blank=True, null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='sistema.centroformacion',
                        verbose_name='Centro de Formación'
                    ),
                ),
            ],
        ),
    ]
