# Generated by Django 5.2.5 on 2025-10-09 16:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maquinaria', '0004_mantenimientoprogramado'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=100, unique=True)),
                ('valor', models.TextField()),
                ('tipo_valor', models.CharField(choices=[('string', 'Texto'), ('integer', 'Numero Entero'), ('float', 'Numero Decimal'), ('boolean', 'Verdadero/Falso'), ('json', 'JSON'), ('date', 'Fecha'), ('datetime', 'Fecha y Hora'), ('email', 'Correo Electronico'), ('url', 'URL')], default='string', max_length=10)),
                ('descripcion', models.TextField(blank=True)),
                ('categoria', models.CharField(default='general', max_length=50)),
                ('publico', models.BooleanField(default=False)),
                ('modificable', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Configuracion',
                'verbose_name_plural': 'Configuraciones',
                'ordering': ['categoria', 'clave'],
            },
        ),
        migrations.CreateModel(
            name='LogActividad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('nivel', models.CharField(choices=[('debug', 'Debug'), ('info', 'Informacion'), ('warning', 'Advertencia'), ('error', 'Error'), ('critical', 'Critico')], default='info', max_length=10)),
                ('modulo', models.CharField(choices=[('usuarios', 'Usuarios'), ('maquinaria', 'Maquinaria'), ('reportes', 'Reportes'), ('ia_assistant', 'Asistente IA'), ('documentos', 'Documentos'), ('sistema', 'Sistema'), ('api', 'API')], default='sistema', max_length=20)),
                ('sesion_id', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('accion', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('objeto_tipo', models.CharField(blank=True, max_length=50)),
                ('objeto_id', models.CharField(blank=True, max_length=100)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('user_agent', models.TextField(blank=True)),
                ('datos_adicionales', models.JSONField(blank=True, default=dict)),
                ('tiempo_ejecucion', models.DurationField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Log de Actividad',
                'verbose_name_plural': 'Logs de Actividad',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='sistema_log_timesta_24e6b0_idx'), models.Index(fields=['usuario', 'timestamp'], name='sistema_log_usuario_880482_idx'), models.Index(fields=['modulo', 'timestamp'], name='sistema_log_modulo_20827a_idx'), models.Index(fields=['nivel'], name='sistema_log_nivel_499901_idx'), models.Index(fields=['accion'], name='sistema_log_accion_5a745c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(choices=[('info', 'Informacion'), ('success', 'Exito'), ('warning', 'Advertencia'), ('error', 'Error'), ('system', 'Sistema')], default='info', max_length=10)),
                ('icono', models.CharField(default='bi-bell', max_length=50)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviada', 'Enviada'), ('leida', 'Leida'), ('archivada', 'Archivada')], default='pendiente', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('fecha_archivado', models.DateTimeField(blank=True, null=True)),
                ('requiere_accion', models.BooleanField(default=False)),
                ('url_accion', models.URLField(blank=True)),
                ('texto_accion', models.CharField(blank=True, max_length=100)),
                ('metadatos', models.JSONField(blank=True, default=dict)),
                ('enviado_por_sistema', models.BooleanField(default=True)),
                ('alerta_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maquinaria.alertamaquina')),
                ('maquina_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maquinaria.maquina')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Notificacion',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['usuario', 'estado'], name='sistema_not_usuario_8d7c23_idx'), models.Index(fields=['fecha_creacion'], name='sistema_not_fecha_c_a61e28_idx'), models.Index(fields=['tipo'], name='sistema_not_tipo_db7141_idx')],
            },
        ),
    ]
