# Generated by Django 5.2.7 on 2025-10-11 16:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
        ('usuarios', '0002_tokenrecuperacionpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logactividad',
            name='modulo',
            field=models.CharField(choices=[('usuarios', 'Usuarios'), ('maquinaria', 'Maquinaria'), ('reportes', 'Reportes'), ('documentos', 'Documentos'), ('sistema', 'Sistema'), ('backups', 'Copias de Seguridad'), ('api', 'API')], default='sistema', max_length=20),
        ),
        migrations.CreateModel(
            name='BackupDatabase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('manual', 'Manual'), ('automatico', 'Automático'), ('programado', 'Programado')], default='manual', max_length=15)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='backups/%Y/%m/')),
                ('ruta_archivo', models.CharField(blank=True, max_length=500)),
                ('tamaño_bytes', models.BigIntegerField(default=0)),
                ('estado', models.CharField(choices=[('creando', 'Creando'), ('completado', 'Completado'), ('error', 'Error'), ('restaurando', 'Restaurando'), ('restaurado', 'Restaurado')], default='creando', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('total_tablas', models.IntegerField(default=0)),
                ('total_registros', models.IntegerField(default=0)),
                ('fecha_restauracion', models.DateTimeField(blank=True, null=True)),
                ('notas_restauracion', models.TextField(blank=True)),
                ('version_django', models.CharField(blank=True, max_length=20)),
                ('version_python', models.CharField(blank=True, max_length=20)),
                ('metadatos', models.JSONField(blank=True, default=dict)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups_creados', to='usuarios.usuario')),
                ('restaurado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups_restaurados', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Copia de Seguridad',
                'verbose_name_plural': 'Copias de Seguridad',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['fecha_creacion'], name='sistema_bac_fecha_c_52ef97_idx'), models.Index(fields=['estado'], name='sistema_bac_estado_dfad15_idx'), models.Index(fields=['creado_por'], name='sistema_bac_creado__3c635b_idx')],
            },
        ),
    ]
