# Generated by Django 5.2.5 on 2026-04-09 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_add_centro_ambiente_formacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True, verbose_name='Número de Ficha')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Programa')),
                ('programa_formacion', models.CharField(max_length=200, verbose_name='Programa de Formación')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('centro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas', to='sistema.centroformacion', verbose_name='Centro de Formación')),
            ],
            options={
                'verbose_name': 'Ficha',
                'verbose_name_plural': 'Fichas',
                'ordering': ['numero'],
            },
        ),
    ]
