# Generated by Django 5.2.7 on 2025-10-10 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0004_mantenimientoprogramado'),
        ('usuarios', '0002_tokenrecuperacionpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaquinaEliminada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_inventario', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=200)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('numero_serie', models.CharField(max_length=100)),
                ('categoria_nombre', models.CharField(max_length=100)),
                ('estado_final', models.CharField(max_length=20)),
                ('condicion_final', models.CharField(max_length=20)),
                ('ubicacion', models.CharField(max_length=200)),
                ('centro_formacion', models.CharField(max_length=200)),
                ('horas_uso_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eficiencia_final', models.DecimalField(decimal_places=2, max_digits=5)),
                ('datos_completos_maquina', models.JSONField(help_text='Todos los datos de la máquina en formato JSON')),
                ('historial_completo', models.JSONField(default=list, help_text='Todo el historial de eventos de la máquina')),
                ('alertas_asociadas', models.JSONField(default=list, help_text='Todas las alertas que tuvo la máquina')),
                ('mantenimientos_realizados', models.JSONField(default=list, help_text='Historial completo de mantenimientos')),
                ('fecha_eliminacion', models.DateTimeField(auto_now_add=True)),
                ('motivo_eliminacion', models.TextField(blank=True)),
                ('observaciones_finales', models.TextField(blank=True)),
                ('total_mantenimientos', models.IntegerField(default=0)),
                ('total_reparaciones', models.IntegerField(default=0)),
                ('total_alertas', models.IntegerField(default=0)),
                ('costo_total_mantenimiento', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('dias_operacion', models.IntegerField(default=0)),
                ('eliminado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maquinas_eliminadas', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Máquina Eliminada',
                'verbose_name_plural': 'Máquinas Eliminadas',
                'ordering': ['-fecha_eliminacion'],
                'indexes': [models.Index(fields=['codigo_inventario'], name='maquinaria__codigo__53abc2_idx'), models.Index(fields=['fecha_eliminacion'], name='maquinaria__fecha_e_89097a_idx')],
            },
        ),
    ]
