# Generated by Django 5.2.5 on 2026-02-10 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0005_maquinaeliminada'),
        ('usuarios', '0003_reconocimientofacial_intentoreconocimientofacial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetoMaquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('serie', models.CharField(blank=True, max_length=100)),
                ('fabricante', models.CharField(blank=True, max_length=200)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('usado', 'Usado'), ('desgastado', 'Desgastado'), ('danado', 'Dañado'), ('reparado', 'Reparado'), ('obsoleto', 'Obsoleto')], default='nuevo', max_length=20)),
                ('medidas', models.CharField(blank=True, help_text='Ej: 30cm x 15cm x 10cm', max_length=200)),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ubicacion_almacen', models.CharField(blank=True, max_length=200)),
                ('fecha_compra', models.DateField(blank=True, null=True)),
                ('fecha_uso', models.DateField(blank=True, null=True)),
                ('fecha_cambio', models.DateField(blank=True, null=True)),
                ('tiempo_uso', models.CharField(blank=True, help_text='Ej: 6 meses, 2 años', max_length=100)),
                ('foto_frontal', models.ImageField(blank=True, null=True, upload_to='objetos/fotos/')),
                ('foto_lateral_derecha', models.ImageField(blank=True, null=True, upload_to='objetos/fotos/')),
                ('foto_lateral_izquierda', models.ImageField(blank=True, null=True, upload_to='objetos/fotos/')),
                ('foto_trasera', models.ImageField(blank=True, null=True, upload_to='objetos/fotos/')),
                ('foto_superior', models.ImageField(blank=True, null=True, upload_to='objetos/fotos/')),
                ('foto_inferior', models.ImageField(blank=True, null=True, upload_to='objetos/fotos/')),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objetos_creados', to='usuarios.usuario')),
                ('maquina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objetos', to='maquinaria.maquina')),
            ],
            options={
                'verbose_name': 'Objeto/Pieza',
                'verbose_name_plural': 'Objetos/Piezas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['nombre'], name='maquinaria__nombre_56b5ac_idx'), models.Index(fields=['maquina'], name='maquinaria__maquina_a955be_idx'), models.Index(fields=['estado'], name='maquinaria__estado_fcd3e3_idx')],
            },
        ),
    ]
