# Generated by Django 5.2.5 on 2026-04-07 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0008_seed_categorias_maquina'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='usomaquinaria',
            new_name='maquinaria__maquina_633d0a_idx',
            old_name='maq_uso_maquina_fecha_idx',
        ),
        migrations.RenameIndex(
            model_name='usomaquinaria',
            new_name='maquinaria__ficha_309046_idx',
            old_name='maq_uso_ficha_idx',
        ),
    ]
