# Generated by Django 5.2.5 on 2026-04-13 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0011_remove_maquina_condicion_eficiencia'),
        ('usuarios', '0005_crear_tipos_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimientoprogramado',
            name='personal_adicional',
            field=models.ManyToManyField(blank=True, related_name='mantenimientos_adicionales', to='usuarios.usuario', verbose_name='Personal adicional'),
        ),
    ]
