# Generated by Django 5.2.5 on 2026-04-27 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinaria', '0012_add_personal_adicional_mantenimiento'),
        ('usuarios', '0005_crear_tipos_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertamaquina',
            name='tecnico_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_asignadas', to='usuarios.usuario'),
        ),
    ]
